use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

// ─── Change this to update the TUI title everywhere ────────────────────────
const TITLE: &str = "LaTeX  Manager";
// ───────────────────────────────────────────────────────────────────────────

fn pyfiglet(title: &str, font: &str) -> Vec<String> {
    let script = format!(
        "import pyfiglet; print(pyfiglet.figlet_format({:?}, font={:?}), end='')",
        title, font
    );
    let out = Command::new("python3")
        .args(["-c", &script])
        .output()
        .expect("build.rs: failed to run python3 — is pyfiglet installed?");
    if !out.status.success() {
        panic!(
            "build.rs: pyfiglet failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    String::from_utf8(out.stdout)
        .unwrap()
        .lines()
        .map(|l| l.to_string())
        .collect()
}

fn lines_to_rs(lines: &[String]) -> String {
    lines
        .iter()
        .map(|l| format!("    {:?}", l))
        .collect::<Vec<_>>()
        .join(",\n")
}

fn main() {
    let large_lines = pyfiglet(TITLE, "ansi_shadow");
    let small_lines = pyfiglet(TITLE, "small");

    let large_height = large_lines.len();
    let small_height = small_lines.len();

    let content = format!(
        "// Auto-generated by build.rs — edit TITLE there to change the header.\n\
         pub const APP_TITLE: &str = {title:?};\n\
         pub const TITLE_LARGE_HEIGHT: u16 = {large_h};\n\
         pub const TITLE_SMALL_HEIGHT: u16 = {small_h};\n\
         pub const TITLE_LARGE: &[&str] = &[\n{large}\n];\n\
         pub const TITLE_SMALL: &[&str] = &[\n{small}\n];\n",
        title = TITLE,
        large_h = large_height,
        small_h = small_height,
        large = lines_to_rs(&large_lines),
        small = lines_to_rs(&small_lines),
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("title.rs");
    fs::write(&dest, content).unwrap();

    // Re-run only if this file changes
    println!("cargo:rerun-if-changed=build.rs");
}
