use figlet_rs::FIGfont;
use std::env;
use std::fs;
use std::path::Path;

// ─── Change these to update the TUI title ─────────────────────────────────
const TITLE: &str = "LaTeX  Manager"; // wide (single-line) version
const LINE1: &str = "LaTeX";          // narrow (two-line) version — word 1
const LINE2: &str = "Manager";        // narrow (two-line) version — word 2
// ───────────────────────────────────────────────────────────────────────────

fn render(text: &str, flf: &str) -> Vec<String> {
    let font = FIGfont::from_content(flf)
        .expect("build.rs: failed to parse FIGfont");
    let figure = font.convert(text)
        .expect("build.rs: failed to render title");
    figure.to_string()
        .lines()
        .map(|l| l.to_string())
        .collect()
}

fn two_line_art(flf: &str) -> Vec<String> {
    let mut out = render(LINE1, flf);
    out.push(String::new());
    out.extend(render(LINE2, flf));
    out
}

fn lines_to_rs(lines: &[String]) -> String {
    lines
        .iter()
        .map(|l| format!("    {:?}", l))
        .collect::<Vec<_>>()
        .join(",\n")
}

fn main() {
    let large_flf = include_str!("fonts/ansi_shadow.flf");
    let small_flf  = include_str!("fonts/small.flf");

    let large_wide   = render(TITLE, large_flf);
    let large_narrow = two_line_art(large_flf);
    let small_wide   = render(TITLE, small_flf);
    let small_narrow = two_line_art(small_flf);

    let content = format!(
        "// Auto-generated by build.rs — edit TITLE / LINE1 / LINE2 to change the header.\n\
         pub const APP_TITLE: &str = {title:?};\n\
         pub const TITLE_LARGE_WIDE_HEIGHT:   u16 = {lwh};\n\
         pub const TITLE_LARGE_NARROW_HEIGHT: u16 = {lnh};\n\
         pub const TITLE_SMALL_WIDE_HEIGHT:   u16 = {swh};\n\
         pub const TITLE_SMALL_NARROW_HEIGHT: u16 = {snh};\n\
         pub const TITLE_LARGE_WIDE:   &[&str] = &[\n{lw}\n];\n\
         pub const TITLE_LARGE_NARROW: &[&str] = &[\n{ln}\n];\n\
         pub const TITLE_SMALL_WIDE:   &[&str] = &[\n{sw}\n];\n\
         pub const TITLE_SMALL_NARROW: &[&str] = &[\n{sn}\n];\n",
        title = TITLE,
        lwh = large_wide.len(),
        lnh = large_narrow.len(),
        swh = small_wide.len(),
        snh = small_narrow.len(),
        lw = lines_to_rs(&large_wide),
        ln = lines_to_rs(&large_narrow),
        sw = lines_to_rs(&small_wide),
        sn = lines_to_rs(&small_narrow),
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("title.rs");
    fs::write(&dest, content).unwrap();

    // Re-run if this file or the font files change
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=fonts/ansi_shadow.flf");
    println!("cargo:rerun-if-changed=fonts/small.flf");
}

