mod config;
mod menu;

use std::env;
use std::fs;
use std::io::{self, BufRead as _, BufReader};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::mpsc::{self, Receiver};
use std::thread;
use std::time::Duration;

// Pull in the figlet art generated by build.rs from TITLE in build.rs
include!(concat!(env!("OUT_DIR"), "/title.rs"));

use crossterm::{
    event::{self, Event, KeyCode, KeyModifiers},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ratatui::{
    backend::CrosstermBackend,
    layout::{Alignment, Constraint, Direction, Layout, Rect},
    style::{Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Clear, List, ListItem, ListState, Paragraph},
    Terminal,
};

fn centered_rect(px: u16, py: u16, r: Rect) -> Rect {
    let vert = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Percentage((100 - py) / 2),
            Constraint::Percentage(py),
            Constraint::Percentage((100 - py) / 2),
        ])
        .split(r);
    Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage((100 - px) / 2),
            Constraint::Percentage(px),
            Constraint::Percentage((100 - px) / 2),
        ])
        .split(vert[1])[1]
}

#[derive(PartialEq)]
enum PopupKind { Output, DirBrowser, TextInput, Confirm }

struct PopupState {
    kind: PopupKind,
    title: String,
    items: Vec<String>,
    paths: Vec<PathBuf>,
    list_state: ListState,
    lines: Vec<String>,
    scroll: usize,
    done: bool,
    rx: Option<Receiver<Option<String>>>,
    input_value: String,
    // ── Recursive / multi-root project browser state (DirBrowser only) ──────
    // The configured roots (label, path) this browser can pick from.
    browse_roots: Vec<(String, PathBuf)>,
    // Navigation stack of directories we've drilled into. Empty means we're
    // at the root picker (only shown when there's more than one root).
    browse_stack: Vec<PathBuf>,
    // true  = recursive multi-root project browser (drills into folders
    //         until one directly contains a file, e.g. main.tex)
    // false = legacy single-level browser (templates, root pickers, recent)
    browse_leaf_check: bool,
    // Whether items[0] is a ".." entry (only meaningful when browse_leaf_check).
    up_entry: bool,
    // Title without the breadcrumb suffix, so it can be rebuilt on navigation.
    base_title: String,
    // ── Type-to-filter (DirBrowser only) ─────────────────────────────────────
    // Typed filter query. `items`/`paths` are the filtered view derived from
    // `all_items`/`all_paths` (the full, unfiltered listing) every time the
    // query or the underlying listing changes.
    filter: String,
    all_items: Vec<String>,
    all_paths: Vec<PathBuf>,
}

impl PopupState {
    fn new_output(title: &str, program: &str, args: &[&str], dir: Option<PathBuf>) -> Self {
        let (tx, rx) = mpsc::channel::<Option<String>>();
        let tx_out = tx.clone();
        let tx_err = tx.clone();
        let mut cmd = Command::new(program);
        cmd.args(args).stdout(Stdio::piped()).stderr(Stdio::piped());
        if let Some(ref d) = dir { cmd.current_dir(d); }
        match cmd.spawn() {
            Ok(mut child) => {
                let stdout = child.stdout.take().unwrap();
                let stderr = child.stderr.take().unwrap();
                let t1 = thread::spawn(move || {
                    for line in BufReader::new(stdout).lines() {
                        if let Ok(l) = line { if tx_out.send(Some(l)).is_err() { break; } }
                    }
                });
                let t2 = thread::spawn(move || {
                    for line in BufReader::new(stderr).lines() {
                        if let Ok(l) = line { if tx_err.send(Some(l)).is_err() { break; } }
                    }
                });
                thread::spawn(move || {
                    let _ = t1.join(); let _ = t2.join();
                    let _ = child.wait(); let _ = tx.send(None);
                });
            }
            Err(e) => {
                let _ = tx.send(Some(format!("Error: {}", e)));
                let _ = tx.send(None);
            }
        }
        let mut ls = ListState::default(); ls.select(Some(0));
        PopupState {
            kind: PopupKind::Output, title: title.to_string(),
            items: vec![], paths: vec![], list_state: ls,
            lines: vec![], scroll: 0, done: false, rx: Some(rx),
            input_value: String::new(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: title.to_string(),
            filter: String::new(), all_items: vec![], all_paths: vec![],
        }
    }

    fn browser_next(&mut self) {
        let n = self.items.len(); if n == 0 { return; }
        let i = (self.list_state.selected().unwrap_or(0) + 1) % n;
        self.list_state.select(Some(i));
    }

    fn browser_prev(&mut self) {
        let n = self.items.len(); if n == 0 { return; }
        let i = (self.list_state.selected().unwrap_or(0) + n - 1) % n;
        self.list_state.select(Some(i));
    }

    fn drain_output(&mut self) {
        if let Some(ref rx) = self.rx {
            loop {
                match rx.try_recv() {
                    Ok(Some(line)) => { self.lines.push(line); self.scroll = self.lines.len().saturating_sub(1); }
                    Ok(None) => { self.done = true; break; }
                    Err(_) => break,
                }
            }
        }
    }

    /// Recompute `items`/`paths` (the displayed, selectable list) from
    /// `all_items`/`all_paths` (the full listing) by applying `filter` as a
    /// case-insensitive substring match. A leading ".." up-entry, if present,
    /// is always kept regardless of the filter text.
    fn apply_filter(&mut self) {
        let q = self.filter.to_lowercase();
        self.items.clear();
        self.paths.clear();

        let start = if self.up_entry && !self.all_items.is_empty() {
            self.items.push(self.all_items[0].clone());
            self.paths.push(self.all_paths[0].clone());
            1
        } else {
            0
        };

        for i in start..self.all_items.len() {
            if q.is_empty() || self.all_items[i].to_lowercase().contains(&q) {
                self.items.push(self.all_items[i].clone());
                self.paths.push(self.all_paths[i].clone());
            }
        }

        if self.items.is_empty() { self.list_state.select(None); }
        else { self.list_state.select(Some(0)); }
    }

    /// Legacy single-level browser: lists one directory's subfolders, and
    /// selecting one immediately confirms it. Used for the templates browser.
    fn new_dir_browser(title: &str, path: &std::path::Path) -> Self {
        let mut entries: Vec<(String, PathBuf)> = fs::read_dir(path)
            .into_iter().flatten().flatten()
            .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
            .map(|e| (e.file_name().to_string_lossy().into_owned(), e.path()))
            .collect();
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        let mut ps = PopupState {
            kind: PopupKind::DirBrowser,
            title: title.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: title.to_string(),
            filter: String::new(),
            all_items: entries.iter().map(|(n, _)| n.clone()).collect(),
            all_paths: entries.into_iter().map(|(_, p)| p).collect(),
        };
        ps.apply_filter();
        ps
    }

    /// Single-level picker over a small list of (label, path) options — used
    /// to choose which configured workspace root a new project should go in.
    fn new_root_picker(title: &str, roots: &[config::ProjectRoot]) -> Self {
        let mut ps = PopupState {
            kind: PopupKind::DirBrowser,
            title: title.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: title.to_string(),
            filter: String::new(),
            all_items: roots.iter().map(|r| r.label.clone()).collect(),
            all_paths: roots.iter().map(|r| r.path.clone()).collect(),
        };
        ps.apply_filter();
        ps
    }

    /// Single-level picker over the MRU recent-projects list. Selecting an
    /// entry opens it directly (no drilling — these are already known leaves).
    fn new_recent_picker(title: &str, recent: &[(String, PathBuf)]) -> Self {
        let mut ps = PopupState {
            kind: PopupKind::DirBrowser,
            title: title.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: title.to_string(),
            filter: String::new(),
            all_items: recent.iter().map(|(l, _)| l.clone()).collect(),
            all_paths: recent.iter().map(|(_, p)| p.clone()).collect(),
        };
        ps.apply_filter();
        ps
    }

    /// Recursive, multi-root project browser. Starts at the root picker if
    /// more than one root is configured (or straight inside the single root
    /// otherwise), and lets the user drill into subfolders. A folder is
    /// treated as a selectable project once it directly contains a file
    /// (e.g. main.tex); folders that only contain subfolders are pure
    /// organisational containers (like a semester or class folder) and are
    /// drilled into instead of selected.
    fn new_project_browser(title: &str, roots: Vec<(String, PathBuf)>) -> Self {
        let mut ps = PopupState {
            kind: PopupKind::DirBrowser,
            title: title.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
            browse_roots: roots,
            browse_stack: vec![],
            browse_leaf_check: true,
            up_entry: false,
            base_title: title.to_string(),
            filter: String::new(), all_items: vec![], all_paths: vec![],
        };
        if ps.browse_roots.len() == 1 {
            let only = ps.browse_roots[0].1.clone();
            ps.browse_stack.push(only);
        }
        ps.refresh_project_browser();
        ps
    }

    /// Recompute items/paths/title for the current position in a recursive
    /// project browser (either the root picker, or a directory listing).
    /// Clears any active filter, since the listing itself just changed.
    fn refresh_project_browser(&mut self) {
        self.all_items.clear();
        self.all_paths.clear();
        self.filter.clear();
        self.up_entry = false;

        if self.browse_stack.is_empty() {
            // Root picker: only reached when more than one root is configured.
            for (label, _) in &self.browse_roots {
                self.all_items.push(label.clone());
            }
            self.all_paths = self.browse_roots.iter().map(|(_, p)| p.clone()).collect();
            self.title = self.base_title.clone();
        } else {
            let cur = self.browse_stack.last().unwrap().clone();
            let show_up = self.browse_stack.len() > 1 || self.browse_roots.len() > 1;
            if show_up {
                self.all_items.push("..".to_string());
                self.all_paths.push(cur.clone()); // placeholder; handled via up_entry, not this path
                self.up_entry = true;
            }
            let mut entries: Vec<(String, PathBuf)> = fs::read_dir(&cur)
                .into_iter().flatten().flatten()
                .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
                .map(|e| (e.file_name().to_string_lossy().into_owned(), e.path()))
                .collect();
            entries.sort_by(|a, b| a.0.cmp(&b.0));
            for (name, path) in entries {
                self.all_items.push(name);
                self.all_paths.push(path);
            }

            let breadcrumb: Vec<String> = self.browse_stack.iter()
                .map(|p| p.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default())
                .collect();
            self.title = format!("{} [{}]", self.base_title, breadcrumb.join(" / "));
        }

        self.apply_filter();
    }

    fn new_text_input(prompt: &str) -> Self {
        Self::new_text_input_prefilled(prompt, "")
    }

    /// Text input popup pre-filled with an initial value (e.g. current name
    /// for a rename), with the cursor at the end.
    fn new_text_input_prefilled(prompt: &str, initial: &str) -> Self {
        PopupState {
            kind: PopupKind::TextInput,
            title: prompt.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: initial.to_string(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: prompt.to_string(),
            filter: String::new(), all_items: vec![], all_paths: vec![],
        }
    }

    /// Yes/no confirmation popup (e.g. "Delete project X?").
    fn new_confirm(message: &str) -> Self {
        PopupState {
            kind: PopupKind::Confirm,
            title: message.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
            browse_roots: vec![], browse_stack: vec![], browse_leaf_check: false,
            up_entry: false, base_title: message.to_string(),
            filter: String::new(), all_items: vec![], all_paths: vec![],
        }
    }
}

/// A directory counts as a selectable "project" (or template) once it
/// directly contains at least one regular file — e.g. main.tex. Pure
/// organisational folders (a semester, a class) hold only subfolders and
/// get drilled into instead.
fn is_leaf_dir(path: &std::path::Path) -> bool {
    fs::read_dir(path).into_iter().flatten().flatten()
        .any(|e| e.file_type().map(|ft| ft.is_file()).unwrap_or(false))
}

/// Build a "RootLabel:relative/path" label for a project, used in the
/// recent-projects list (e.g. "Uni:2026-Fall/CS301/hw1").
fn compute_project_label(roots: &[(String, PathBuf)], path: &std::path::Path) -> String {
    for (label, root_path) in roots {
        if let Ok(rel) = path.strip_prefix(root_path) {
            return format!("{}:{}", label, rel.display());
        }
    }
    path.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_else(|| path.display().to_string())
}

// Tracks multi-step workflows (e.g. prompt → copy → nvim → compile)
enum WorkflowState {
    WaitingForBlankRoot    { templates_dir: PathBuf },
    WaitingForBlankName    { templates_dir: PathBuf, projects_dir: PathBuf, root_label: String },
    WaitingForTemplateRoot { templates_dir: PathBuf },
    WaitingForTemplate     { projects_dir: PathBuf, root_label: String },
    WaitingForTemplateName { template_path: PathBuf, projects_dir: PathBuf, root_label: String },
    WaitingForProject,
    WaitingForRecentProject,
    WaitingForMindmapProject { tui_dir: PathBuf },
    WaitingForEditorChoice,
    // Delete/rename, triggered from inside the recursive project browser.
    // `resume` restores whichever browser flow (open / mindmap) was active,
    // and the browse context lets us reopen the browser at the same spot.
    WaitingForDeleteConfirm {
        target: PathBuf,
        browse_roots: Vec<(String, PathBuf)>,
        browse_stack: Vec<PathBuf>,
        base_title: String,
        resume: Box<WorkflowState>,
    },
    WaitingForRenameName {
        target: PathBuf,
        browse_roots: Vec<(String, PathBuf)>,
        browse_stack: Vec<PathBuf>,
        base_title: String,
        resume: Box<WorkflowState>,
    },
}

struct App {
    list_state: ListState,
    message: Option<String>,
    popup: Option<PopupState>,
    workflow: Option<WorkflowState>,
    pending_pdf: Option<PathBuf>,
}

impl App {
    fn new() -> Self {
        let mut s = ListState::default(); s.select(Some(0));
        App { list_state: s, popup: None, message: None, workflow: None, pending_pdf: None }
    }
    fn main_next(&mut self) {
        let i = (self.list_state.selected().unwrap_or(0) + 1) % menu::ITEMS.len();
        self.list_state.select(Some(i));
    }
    fn main_prev(&mut self) {
        let n = menu::ITEMS.len();
        let i = (self.list_state.selected().unwrap_or(0) + n - 1) % n;
        self.list_state.select(Some(i));
    }
}

// Internal TUI navigation actions (distinct from menu::Action which is user-facing)
enum Action {
    Quit, MainNext, MainPrev,
    ClosePopup,
    BrowserNext, BrowserPrev,
    BrowserUp,
    OutputScrollUp, OutputScrollDown,
    DirBrowserConfirm,
    FilterChar(char),
    FilterBackspace,
    FilterClear,
    DeletePrompt,
    RenamePrompt,
    ConfirmYes,
    ConfirmNo,
    TextInputConfirm,
    TextInputChar(char),
    TextInputBackspace,
    MenuAction(menu::Action),
}

// ── LaTeX helpers ────────────────────────────────────────────────────────────

/// Create `.build/` and any subdirectories needed for `\include` / `\input` paths.
fn prepare_build_dir(project_dir: &std::path::Path) {
    let build = project_dir.join(".build");
    let _ = fs::create_dir_all(&build);
    if let Ok(content) = fs::read_to_string(project_dir.join("main.tex")) {
        for line in content.lines() {
            for prefix in &["\\include{", "\\input{"] {
                if let Some(start) = line.find(prefix) {
                    let rest = &line[start + prefix.len()..];
                    if let Some(end) = rest.find('}') {
                        let path = rest[..end].trim();
                        if path.contains('/') {
                            if let Some(parent) = std::path::Path::new(path).parent() {
                                let _ = fs::create_dir_all(build.join(parent));
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Copy a directory recursively, excluding certain files and extensions.
fn copy_dir_filtered(src: &std::path::Path, dst: &std::path::Path) -> io::Result<()> {
    const EXCLUDE_NAMES: &[&str] = &[".build", "missfont.log", "main.pdf"];
    const EXCLUDE_EXTS: &[&str] = &["aux", "log", "fdb_latexmk", "fls", "synctex.gz", "toc", "out"];

    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_name = entry.file_name();
        let name = file_name.to_string_lossy();

        if EXCLUDE_NAMES.contains(&name.as_ref()) {
            continue;
        }
        if let Some(ext) = std::path::Path::new(name.as_ref()).extension() {
            if EXCLUDE_EXTS.contains(&ext.to_string_lossy().as_ref()) {
                continue;
            }
        }

        let src_path = entry.path();
        let dst_path = dst.join(&file_name);
        let ty = entry.file_type()?;
        if ty.is_dir() {
            copy_dir_filtered(&src_path, &dst_path)?;
        } else if ty.is_file() {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Prepare the build directory then spawn a compile output popup.
fn launch_compile(project_dir: PathBuf, compiler: &str) -> PopupState {
    prepare_build_dir(&project_dir);
    // Run the compiler twice so refs/TOC are resolved.
    // Don't force TEXINPUTS — let TeX use system defaults which work better on all platforms.
    let script = format!(
        "{compiler} -interaction=nonstopmode -output-directory=.build main.tex 2>&1 && \
         {compiler} -interaction=nonstopmode -output-directory=.build main.tex",
        compiler = compiler
    );
    let shell_args = ["-c", script.as_str()];
    PopupState::new_output("Compiling", "sh", &shell_args, Some(project_dir))
}

fn open_editor_in_project(
    editor: &str,
    project_dir: &std::path::Path,
    terminal: &mut Terminal<CrosstermBackend<io::Stdout>>,
) -> io::Result<()> {
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;

    let editor_lc = editor.trim().to_lowercase();
    let mut cmd = if matches!(editor_lc.as_str(), "vscode" | "code") {
        let mut cmd = Command::new("code");
        cmd.arg(".").arg("-g").arg("main.tex");
        cmd
    } else {
        let mut cmd = Command::new("nvim");
        cmd.arg("main.tex");
        cmd
    };
    cmd.current_dir(project_dir);
    let status = cmd.status();

    // Always restore the terminal, even if the editor errored or exited non-zero.
    enable_raw_mode()?;
    execute!(terminal.backend_mut(), EnterAlternateScreen)?;
    terminal.clear()?;

    let status = status?;
    if !status.success() {
        return Err(io::Error::new(
            io::ErrorKind::Other,
            format!("Editor exited with status {}", status),
        ));
    }
    Ok(())
}

fn open_file_in_editor(
    editor: &str,
    file_path: &std::path::Path,
    terminal: &mut Terminal<CrosstermBackend<io::Stdout>>,
) -> io::Result<()> {
    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;

    let editor_lc = editor.trim().to_lowercase();
    let mut cmd = if matches!(editor_lc.as_str(), "vscode" | "code") {
        let mut cmd = Command::new("code");
        cmd.arg("-g").arg(file_path);
        cmd
    } else {
        let mut cmd = Command::new("nvim");
        cmd.arg(file_path);
        cmd
    };

    if let Some(parent) = file_path.parent() {
        cmd.current_dir(parent);
    }
    let status = cmd.status();

    // Always restore the terminal, even if the editor errored or exited non-zero.
    enable_raw_mode()?;
    execute!(terminal.backend_mut(), EnterAlternateScreen)?;
    terminal.clear()?;

    let status = status?;
    if !status.success() {
        return Err(io::Error::new(
            io::ErrorKind::Other,
            format!("Editor exited with status {}", status),
        ));
    }
    Ok(())
}

fn main() -> io::Result<()> {
    let mut cfg = config::load();

    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    let mut app = App::new();
    let mut quit = false;

    let labels: Vec<&str> = menu::ITEMS.iter().map(|m| m.label).collect();

    while !quit {
        if let Some(ref mut p) = app.popup {
            if p.kind == PopupKind::Output { p.drain_output(); }
        }

        terminal.draw(|f| {
            let area = f.area();

            let content_area = Rect::new(0, 0, area.width, area.height);

            let chunks = Layout::default()
                .direction(Direction::Vertical)
                .constraints([
                    Constraint::Min(0),
                    Constraint::Length(3),
                ])
                .split(content_area);

            // Large font is always two lines (LaTeX / Manager stacked).
            // Small font switches to two lines when the window is narrow.
            let use_large = area.height >= 35;
            let small_wide = area.width >= 56;

            let art_height: u16 = if area.height < 20 { 1 }
                else if use_large { TITLE_LARGE_NARROW_HEIGHT }
                else if small_wide { TITLE_SMALL_WIDE_HEIGHT }
                else { TITLE_SMALL_NARROW_HEIGHT };

            let ascii_lines: Vec<Line> = if area.height < 20 {
                vec![Line::from(Span::styled(APP_TITLE, Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD)))]
            } else {
                let art: &[&str] = if use_large {
                    TITLE_LARGE_NARROW
                } else if small_wide {
                    TITLE_SMALL_WIDE
                } else {
                    TITLE_SMALL_NARROW
                };
                art.iter().map(|l| Line::from(Span::styled(*l, Style::default().fg(cfg.accent_color)))).collect()
            };

            // Outer block — one unified widget for art + items
            let menu_block = Block::default().borders(Borders::ALL);
            let menu_inner = menu_block.inner(chunks[0]);
            f.render_widget(menu_block, chunks[0]);

            // Split inner area: ASCII art top, list items below
            let inner_chunks = Layout::default()
                .direction(Direction::Vertical)
                .constraints([
                    Constraint::Length(art_height + 1),  // art lines + 1 blank gap
                    Constraint::Min(0),
                ])
                .split(menu_inner);

            let mut art_with_gap = ascii_lines;
            art_with_gap.push(Line::raw(""));
            let art = Paragraph::new(art_with_gap).alignment(Alignment::Center);
            f.render_widget(art, inner_chunks[0]);

            // Offset the list rect so "> item" block is centered as a whole
            let inner_w = menu_inner.width as usize;
            let max_item_len = labels.iter().map(|s| s.len()).max().unwrap_or(0);
            let sym_len = 2; // "> "
            let pad_left = ((inner_w.saturating_sub(max_item_len + sym_len)) / 2) as u16;
            let list_rect = Rect::new(
                inner_chunks[1].x + pad_left,
                inner_chunks[1].y,
                inner_chunks[1].width.saturating_sub(pad_left),
                inner_chunks[1].height,
            );
            let main_items: Vec<ListItem> = labels.iter()
                .map(|i| ListItem::new(*i))
                .collect();
            let main_list = List::new(main_items)
                .highlight_style(Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD))
                .highlight_symbol("> ");
            f.render_stateful_widget(main_list, list_rect, &mut app.list_state);

            let footer_text = if let Some(ref msg) = app.message {
                msg.clone()
            } else {
                "↑↓ or j/k to navigate  |  Enter select  |  q quit".to_string()
            };
            let footer = Paragraph::new(footer_text)
                .alignment(Alignment::Center)
                .style(Style::default().fg(cfg.footer_color))
                .block(Block::default().borders(Borders::ALL));
            f.render_widget(footer, chunks[1]);

            // Spotlight-style popup rendered on top of content area
            if let Some(ref mut popup) = app.popup {
                match popup.kind {
                    PopupKind::DirBrowser => {
                        let popup_area = centered_rect(60, 70, content_area);
                        f.render_widget(Clear, popup_area);
                        let items: Vec<ListItem> = popup.items.iter()
                            .map(|i| ListItem::new(i.as_str())).collect();
                        let hint = if popup.filter.is_empty() {
                            if popup.browse_leaf_check {
                                "\u{2191}\u{2193} navigate  type to filter  \u{23ce} select  ^R rename  ^D delete  Esc cancel".to_string()
                            } else {
                                "\u{2191}\u{2193} navigate  type to filter  \u{23ce} select  Esc cancel".to_string()
                            }
                        } else {
                            format!("filter: {}\u{258c}   Esc clear/cancel  \u{23ce} select", popup.filter)
                        };
                        let list = List::new(items)
                            .block(Block::default()
                                .title(format!(" {}  ({}) ", popup.title, hint))
                                .borders(Borders::ALL))
                            .highlight_style(Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD))
                            .highlight_symbol("> ");
                        f.render_stateful_widget(list, popup_area, &mut popup.list_state);
                    }
                    PopupKind::Confirm => {
                        let popup_area = centered_rect(55, 22, content_area);
                        f.render_widget(Clear, popup_area);
                        let widget = Paragraph::new(vec![
                            Line::raw(""),
                            Line::from(format!("  {}", popup.title)),
                            Line::raw(""),
                            Line::from(Span::styled(
                                "  y confirm  |  n / Esc cancel",
                                Style::default().fg(cfg.footer_color),
                            )),
                        ])
                        .block(Block::default().borders(Borders::ALL));
                        f.render_widget(widget, popup_area);
                    }
                    PopupKind::Output => {
                        let popup_area = centered_rect(80, 80, content_area);
                        f.render_widget(Clear, popup_area);
                        let inner_h = popup_area.height.saturating_sub(2) as usize;
                        let start = popup.scroll.saturating_sub(inner_h.saturating_sub(1));
                        let visible: Vec<ListItem> = popup.lines.iter()
                            .skip(start).take(inner_h)
                            .map(|l| ListItem::new(l.as_str())).collect();
                        let status = if popup.done { " [done - Esc to close]" } else { " [running...]" };
                        let list = List::new(visible).block(
                            Block::default()
                                .title(format!(" {}{} ", popup.title, status))
                                .borders(Borders::ALL));
                        f.render_widget(list, popup_area);
                    }
                    PopupKind::TextInput => {
                        let popup_area = centered_rect(55, 22, content_area);
                        f.render_widget(Clear, popup_area);
                        let display = format!("{}\u{258c}", popup.input_value);
                        let widget = Paragraph::new(vec![
                            Line::raw(""),
                            Line::from(format!("  {}", display)),
                            Line::raw(""),
                            Line::from(Span::styled(
                                "  \u{23ce} confirm  |  Esc cancel",
                                Style::default().fg(cfg.footer_color),
                            )),
                        ])
                        .block(Block::default()
                            .title(format!(" {} ", popup.title))
                            .borders(Borders::ALL));
                        f.render_widget(widget, popup_area);
                    }
                }
            }

        })?;

        let streaming = matches!(&app.popup, Some(p) if p.kind == PopupKind::Output && !p.done);
        let timeout = if streaming { Duration::from_millis(100) } else { Duration::from_secs(60) };
        if !event::poll(timeout)? { continue; }

        let Event::Key(key) = event::read()? else { continue; };
        app.message = None;

        let action: Option<Action> = if let Some(ref popup) = app.popup {
            match popup.kind {
                PopupKind::DirBrowser => match key.code {
                    KeyCode::Char('d') if key.modifiers.contains(KeyModifiers::CONTROL) => Some(Action::DeletePrompt),
                    KeyCode::Char('r') if key.modifiers.contains(KeyModifiers::CONTROL) => Some(Action::RenamePrompt),
                    KeyCode::Up    => Some(Action::BrowserPrev),
                    KeyCode::Down  => Some(Action::BrowserNext),
                    KeyCode::Left  => Some(Action::BrowserUp),
                    KeyCode::Esc   => {
                        if popup.filter.is_empty() { Some(Action::ClosePopup) } else { Some(Action::FilterClear) }
                    }
                    KeyCode::Enter => Some(Action::DirBrowserConfirm),
                    KeyCode::Backspace => {
                        if popup.filter.is_empty() { Some(Action::BrowserUp) } else { Some(Action::FilterBackspace) }
                    }
                    KeyCode::Char(c) => Some(Action::FilterChar(c)),
                    _ => None,
                },
                PopupKind::Confirm => match key.code {
                    KeyCode::Char('y') | KeyCode::Char('Y') | KeyCode::Enter => Some(Action::ConfirmYes),
                    KeyCode::Char('n') | KeyCode::Char('N') | KeyCode::Esc   => Some(Action::ConfirmNo),
                    _ => None,
                },
                PopupKind::TextInput => match key.code {
                    KeyCode::Esc       => Some(Action::ClosePopup),
                    KeyCode::Enter     => Some(Action::TextInputConfirm),
                    KeyCode::Char(c)   => Some(Action::TextInputChar(c)),
                    KeyCode::Backspace => Some(Action::TextInputBackspace),
                    _ => None,
                },
                PopupKind::Output => match key.code {
                    KeyCode::Up   | KeyCode::Char('k') => Some(Action::OutputScrollUp),
                    KeyCode::Down | KeyCode::Char('j') => Some(Action::OutputScrollDown),
                    KeyCode::Esc if popup.done => Some(Action::ClosePopup),
                    _ => None,
                },
            }
        } else {
            match key.code {
                KeyCode::Up     | KeyCode::Char('k')    => Some(Action::MainPrev),
                KeyCode::Down   | KeyCode::Char('j')    => Some(Action::MainNext),
                KeyCode::Char('q') | KeyCode::Esc => Some(Action::Quit),
                KeyCode::Enter => {
                    let idx = app.list_state.selected().unwrap_or(0);
                    menu::ITEMS.get(idx)
                        .map(|item| Action::MenuAction((item.action)(&cfg)))
                }
                _ => None,
            }
        };

        if let Some(action) = action {
            match action {
                Action::Quit => quit = true,
                Action::MainNext => app.main_next(),
                Action::MainPrev => app.main_prev(),
                Action::ClosePopup => {
                    // When closing a finished compile popup, open the PDF
                    if matches!(&app.popup, Some(p) if p.kind == PopupKind::Output) {
                        if let Some(pdf) = app.pending_pdf.take() {
                            if pdf.exists() {
                                disable_raw_mode()?;
                                execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                                
                                // Try pdf_viewer command (supports shell aliases/commands)
                                let pdf_path = pdf.to_str().unwrap_or(".");
                                let ok = Command::new("sh")
                                    .arg("-c")
                                    .arg(format!("{} \"{}\"", cfg.pdf_viewer, pdf_path))
                                    .status()
                                    .map(|s| s.success())
                                    .unwrap_or(false);
                                
                                if !ok {
                                    app.message = Some(format!(
                                        "Could not open PDF with '{}'. Check tui.conf pdf_viewer setting.",
                                        cfg.pdf_viewer
                                    ));
                                }
                                
                                enable_raw_mode()?;
                                execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                                terminal.clear()?;
                            } else {
                                app.message = Some(
                                    "Compilation failed — check .build/main.log for errors.".to_string()
                                );
                            }
                        }
                    }
                    app.workflow = None;
                    app.popup = None;
                }
                // (ClosePopupWithMsg removed — no longer needed)
                Action::BrowserNext => { if let Some(ref mut p) = app.popup { p.browser_next(); } }
                Action::BrowserPrev => { if let Some(ref mut p) = app.popup { p.browser_prev(); } }
                Action::BrowserUp => {
                    if let Some(p) = app.popup.as_mut() {
                        if p.browse_leaf_check && !p.browse_stack.is_empty() {
                            if p.browse_stack.len() > 1 { p.browse_stack.pop(); }
                            else { p.browse_stack.clear(); }
                            p.refresh_project_browser();
                        }
                    }
                }
                Action::FilterChar(c) => {
                    if let Some(p) = app.popup.as_mut() { p.filter.push(c); p.apply_filter(); }
                }
                Action::FilterBackspace => {
                    if let Some(p) = app.popup.as_mut() { p.filter.pop(); p.apply_filter(); }
                }
                Action::FilterClear => {
                    if let Some(p) = app.popup.as_mut() { p.filter.clear(); p.apply_filter(); }
                }
                Action::OutputScrollUp => {
                    if let Some(ref mut p) = app.popup { p.scroll = p.scroll.saturating_sub(1); }
                }
                Action::OutputScrollDown => {
                    if let Some(ref mut p) = app.popup {
                        p.scroll = (p.scroll + 1).min(p.lines.len().saturating_sub(1));
                    }
                }
                Action::DirBrowserConfirm => {
                    let recursive = matches!(&app.popup, Some(p) if p.browse_leaf_check);

                    if recursive {
                        // Recursive multi-root project browser: either navigate
                        // (root picker → dir → subdir → ...) or, once a directory
                        // that directly holds files is chosen, finalize the pick.
                        enum Nav { Navigated, Nothing, Selected(PathBuf) }

                        let nav = {
                            let popup = app.popup.as_mut().unwrap();
                            let idx = popup.list_state.selected();
                            match idx {
                                Some(0) if popup.up_entry => {
                                    if popup.browse_stack.len() > 1 { popup.browse_stack.pop(); }
                                    else { popup.browse_stack.clear(); }
                                    popup.refresh_project_browser();
                                    Nav::Navigated
                                }
                                Some(i) if popup.browse_stack.is_empty() => {
                                    match popup.browse_roots.get(i).map(|(_, p)| p.clone()) {
                                        Some(root_path) => {
                                            popup.browse_stack.push(root_path);
                                            popup.refresh_project_browser();
                                            Nav::Navigated
                                        }
                                        None => Nav::Nothing,
                                    }
                                }
                                Some(i) => {
                                    match popup.paths.get(i).cloned() {
                                        Some(chosen) if is_leaf_dir(&chosen) => Nav::Selected(chosen),
                                        Some(chosen) => {
                                            popup.browse_stack.push(chosen);
                                            popup.refresh_project_browser();
                                            Nav::Navigated
                                        }
                                        None => Nav::Nothing,
                                    }
                                }
                                None => Nav::Nothing,
                            }
                        };

                        match nav {
                            Nav::Navigated => {}
                            Nav::Nothing => { app.message = Some("Nothing selected.".to_string()); }
                            Nav::Selected(project_dir) => {
                                let roots_snapshot = app.popup.as_ref().map(|p| p.browse_roots.clone()).unwrap_or_default();
                                app.popup = None;
                                match app.workflow.take() {
                                    Some(WorkflowState::WaitingForProject) => {
                                        if let Err(e) = open_editor_in_project(&cfg.editor, &project_dir, &mut terminal) {
                                            app.message = Some(format!("Failed to launch editor: {}", e));
                                        }
                                        config::record_recent(&compute_project_label(&roots_snapshot, &project_dir), &project_dir);
                                        if cfg.auto_compile {
                                            app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                            app.popup = Some(launch_compile(project_dir, &cfg.latex_compiler));
                                        } else {
                                            app.message = Some("Auto-compile disabled.".to_string());
                                        }
                                    }
                                    Some(WorkflowState::WaitingForMindmapProject { tui_dir }) => {
                                        let script = tui_dir.join("tui").join("latex-to-mindmap-portable.sh");
                                        app.popup = Some(PopupState::new_output(
                                            "Converting to mindmap",
                                            "bash",
                                            &[script.to_str().unwrap_or("."), project_dir.to_str().unwrap_or(".")],
                                            None,
                                        ));
                                    }
                                    _ => { app.message = Some("Nothing selected.".to_string()); }
                                }
                            }
                        }
                    } else {
                        // Legacy single-level browser: templates list, root
                        // picker, or the recent-projects list. Capture both
                        // the label and path, since some flows need the label
                        // (e.g. as the chosen workspace's display name).
                        let selected = app.popup.as_ref().and_then(|p| {
                            p.list_state.selected().and_then(|i| {
                                let path = p.paths.get(i)?.clone();
                                let label = p.items.get(i).cloned().unwrap_or_default();
                                Some((label, path))
                            })
                        });
                        let workflow = app.workflow.take();
                        app.popup = None;
                        match (selected, workflow) {
                            (Some((label, root_path)), Some(WorkflowState::WaitingForBlankRoot { templates_dir })) => {
                                app.workflow = Some(WorkflowState::WaitingForBlankName { templates_dir, projects_dir: root_path, root_label: label });
                                app.popup = Some(PopupState::new_text_input("Enter project name:"));
                            }
                            (Some((label, root_path)), Some(WorkflowState::WaitingForTemplateRoot { templates_dir })) => {
                                app.workflow = Some(WorkflowState::WaitingForTemplate { projects_dir: root_path, root_label: label });
                                app.popup = Some(PopupState::new_dir_browser("Select a template:", &templates_dir));
                            }
                            (Some((_, template_path)), Some(WorkflowState::WaitingForTemplate { projects_dir, root_label })) => {
                                app.workflow = Some(WorkflowState::WaitingForTemplateName { template_path, projects_dir, root_label });
                                app.popup = Some(PopupState::new_text_input("Enter project name:"));
                            }
                            (Some((label, project_dir)), Some(WorkflowState::WaitingForRecentProject)) => {
                                if let Err(e) = open_editor_in_project(&cfg.editor, &project_dir, &mut terminal) {
                                    app.message = Some(format!("Failed to launch editor: {}", e));
                                }
                                config::record_recent(&label, &project_dir); // bump to front
                                if cfg.auto_compile {
                                    app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                    app.popup = Some(launch_compile(project_dir, &cfg.latex_compiler));
                                } else {
                                    app.message = Some("Auto-compile disabled.".to_string());
                                }
                            }
                            _ => { app.message = Some("Nothing selected.".to_string()); }
                        }
                    }
                }
                Action::DeletePrompt => {
                    if let Some(p) = app.popup.as_ref() {
                        if p.browse_leaf_check && !p.browse_stack.is_empty() {
                            let idx = p.list_state.selected();
                            let skip_up = p.up_entry;
                            if let Some(i) = idx {
                                if !(skip_up && i == 0) {
                                    if let Some(target) = p.paths.get(i).cloned() {
                                        let name = target.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
                                        let msg = if is_leaf_dir(&target) {
                                            format!("Delete project '{}'? This cannot be undone.", name)
                                        } else {
                                            format!("Delete folder '{}' and EVERYTHING inside it? This cannot be undone.", name)
                                        };
                                        let resume = app.workflow.take().unwrap_or(WorkflowState::WaitingForProject);
                                        let browse_roots = p.browse_roots.clone();
                                        let browse_stack = p.browse_stack.clone();
                                        let base_title = p.base_title.clone();
                                        app.workflow = Some(WorkflowState::WaitingForDeleteConfirm {
                                            target, browse_roots, browse_stack, base_title, resume: Box::new(resume),
                                        });
                                        app.popup = Some(PopupState::new_confirm(&msg));
                                    }
                                }
                            }
                        }
                    }
                }
                Action::RenamePrompt => {
                    if let Some(p) = app.popup.as_ref() {
                        if p.browse_leaf_check && !p.browse_stack.is_empty() {
                            let idx = p.list_state.selected();
                            let skip_up = p.up_entry;
                            if let Some(i) = idx {
                                if !(skip_up && i == 0) {
                                    if let Some(target) = p.paths.get(i).cloned() {
                                        let name = target.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
                                        let resume = app.workflow.take().unwrap_or(WorkflowState::WaitingForProject);
                                        let browse_roots = p.browse_roots.clone();
                                        let browse_stack = p.browse_stack.clone();
                                        let base_title = p.base_title.clone();
                                        app.workflow = Some(WorkflowState::WaitingForRenameName {
                                            target, browse_roots, browse_stack, base_title, resume: Box::new(resume),
                                        });
                                        app.popup = Some(PopupState::new_text_input_prefilled("Rename to:", &name));
                                    }
                                }
                            }
                        }
                    }
                }
                Action::ConfirmYes => {
                    app.popup = None;
                    match app.workflow.take() {
                        Some(WorkflowState::WaitingForDeleteConfirm { target, browse_roots, browse_stack, base_title, resume }) => {
                            match fs::remove_dir_all(&target) {
                                Ok(()) => app.message = Some("Deleted.".to_string()),
                                Err(e) => app.message = Some(format!("Failed to delete: {}", e)),
                            }
                            let mut popup = PopupState::new_project_browser(&base_title, browse_roots);
                            popup.browse_stack = browse_stack;
                            popup.refresh_project_browser();
                            app.popup = Some(popup);
                            app.workflow = Some(*resume);
                        }
                        _ => {}
                    }
                }
                Action::ConfirmNo => {
                    app.popup = None;
                    match app.workflow.take() {
                        Some(WorkflowState::WaitingForDeleteConfirm { browse_roots, browse_stack, base_title, resume, .. }) => {
                            let mut popup = PopupState::new_project_browser(&base_title, browse_roots);
                            popup.browse_stack = browse_stack;
                            popup.refresh_project_browser();
                            app.popup = Some(popup);
                            app.workflow = Some(*resume);
                        }
                        _ => { app.workflow = None; }
                    }
                }
                Action::TextInputChar(c) => {
                    if let Some(ref mut p) = app.popup { p.input_value.push(c); }
                }
                Action::TextInputBackspace => {
                    if let Some(ref mut p) = app.popup { p.input_value.pop(); }
                }
                Action::TextInputConfirm => {
                    let name = app.popup.as_ref()
                        .map(|p| p.input_value.trim().to_string())
                        .unwrap_or_default();
                    if name.is_empty() {
                        app.message = Some("Name cannot be empty.".to_string());
                    } else {
                        let workflow = app.workflow.take();
                        app.popup = None;
                        match workflow {
                            Some(WorkflowState::WaitingForBlankName { templates_dir, projects_dir, root_label }) => {
                                let project_dir = projects_dir.join(&name);
                                let _ = fs::create_dir_all(&project_dir);
                                let src = templates_dir.join("main.tex");
                                if src.exists() { let _ = fs::copy(&src, project_dir.join("main.tex")); }
                                if let Err(e) = open_editor_in_project(&cfg.editor, &project_dir, &mut terminal) {
                                    app.message = Some(format!("Failed to launch editor: {}", e));
                                }
                                config::record_recent(&format!("{}:{}", root_label, name), &project_dir);
                                if cfg.auto_compile {
                                    app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                    app.popup = Some(launch_compile(project_dir, &cfg.latex_compiler));
                                } else {
                                    app.message = Some("Auto-compile disabled.".to_string());
                                }
                            }
                            Some(WorkflowState::WaitingForTemplateName { template_path, projects_dir, root_label }) => {
                                let project_dir = projects_dir.join(&name);
                                let _ = fs::create_dir_all(&project_dir);
                                if let Err(e) = copy_dir_filtered(&template_path, &project_dir) {
                                    app.message = Some(format!("Failed to copy template: {}", e));
                                }
                                if let Err(e) = open_editor_in_project(&cfg.editor, &project_dir, &mut terminal) {
                                    app.message = Some(format!("Failed to launch editor: {}", e));
                                }
                                config::record_recent(&format!("{}:{}", root_label, name), &project_dir);
                                if cfg.auto_compile {
                                    app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                    app.popup = Some(launch_compile(project_dir, &cfg.latex_compiler));
                                } else {
                                    app.message = Some("Auto-compile disabled.".to_string());
                                }
                            }
                            Some(WorkflowState::WaitingForRenameName { target, browse_roots, browse_stack, base_title, resume }) => {
                                let parent = target.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| PathBuf::from("."));
                                let new_path = parent.join(&name);
                                match fs::rename(&target, &new_path) {
                                    Ok(()) => app.message = Some(format!("Renamed to '{}'.", name)),
                                    Err(e) => app.message = Some(format!("Failed to rename: {}", e)),
                                }
                                let mut popup = PopupState::new_project_browser(&base_title, browse_roots);
                                popup.browse_stack = browse_stack;
                                popup.refresh_project_browser();
                                app.popup = Some(popup);
                                app.workflow = Some(*resume);
                            }
                            Some(WorkflowState::WaitingForEditorChoice) => {
                                let choice = name.to_lowercase();
                                let normalized = match choice.as_str() {
                                    "nvim" => Some("nvim"),
                                    "vscode" | "code" => Some("vscode"),
                                    _ => None,
                                };

                                if let Some(editor) = normalized {
                                    cfg.editor = editor.to_string();
                                    if let Err(e) = config::save_editor(&cfg.editor) {
                                        app.message = Some(format!("Failed to save editor: {}", e));
                                    } else {
                                        app.message = Some(format!("Editor set to {}", cfg.editor));
                                    }
                                } else {
                                    app.message = Some("Editor must be 'nvim' or 'vscode'.".to_string());
                                }
                            }
                            _ => {}
                        }
                    }
                }
                Action::MenuAction(menu_action) => match menu_action {
                    menu::Action::Quit => quit = true,
                    menu::Action::LaunchOutput { title, program, args, dir } => {
                        let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
                        app.popup = Some(PopupState::new_output(&title, &program, &args_ref, dir));
                    }
                    menu::Action::RunInteractive { program, args, dir } => {
                        disable_raw_mode()?;
                        execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                        let mut cmd = Command::new(&program);
                        cmd.args(&args);
                        if let Some(ref d) = dir { cmd.current_dir(d); }
                        let _ = cmd.status();
                        enable_raw_mode()?;
                        execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                        terminal.clear()?;
                    }
                    menu::Action::CreateBlankProject { templates_dir, projects_roots } => {
                        if projects_roots.len() <= 1 {
                            let (projects_dir, root_label) = projects_roots.get(0)
                                .map(|r| (r.path.clone(), r.label.clone()))
                                .unwrap_or_else(|| (cfg.workspace_root.join("projects"), "Projects".to_string()));
                            app.workflow = Some(WorkflowState::WaitingForBlankName { templates_dir, projects_dir, root_label });
                            app.popup = Some(PopupState::new_text_input("Enter project name:"));
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForBlankRoot { templates_dir });
                            app.popup = Some(PopupState::new_root_picker("Select workspace:", &projects_roots));
                        }
                    }
                    menu::Action::CreateFromTemplate { templates_dir, projects_roots } => {
                        if !templates_dir.is_dir() {
                            app.message = Some(format!("Templates dir not found: {}", templates_dir.display()));
                        } else if projects_roots.len() <= 1 {
                            let (projects_dir, root_label) = projects_roots.get(0)
                                .map(|r| (r.path.clone(), r.label.clone()))
                                .unwrap_or_else(|| (cfg.workspace_root.join("projects"), "Projects".to_string()));
                            app.workflow = Some(WorkflowState::WaitingForTemplate { projects_dir, root_label });
                            app.popup = Some(PopupState::new_dir_browser("Select a template:", &templates_dir));
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForTemplateRoot { templates_dir });
                            app.popup = Some(PopupState::new_root_picker("Select workspace:", &projects_roots));
                        }
                    }
                    menu::Action::OpenLatexProject { projects_roots } => {
                        if projects_roots.is_empty() {
                            app.message = Some("No project roots configured.".to_string());
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForProject);
                            let roots = projects_roots.iter().map(|r| (r.label.clone(), r.path.clone())).collect();
                            app.popup = Some(PopupState::new_project_browser("Select a project:", roots));
                        }
                    }
                    menu::Action::OpenRecent => {
                        let recent = config::load_recent();
                        if recent.is_empty() {
                            app.message = Some("No recent projects yet.".to_string());
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForRecentProject);
                            app.popup = Some(PopupState::new_recent_picker("Recent projects:", &recent));
                        }
                    }
                    menu::Action::ConvertToMindmap { projects_roots, tui_dir } => {
                        if projects_roots.is_empty() {
                            app.message = Some("No project roots configured.".to_string());
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForMindmapProject { tui_dir });
                            let roots = projects_roots.iter().map(|r| (r.label.clone(), r.path.clone())).collect();
                            app.popup = Some(PopupState::new_project_browser("Select a project to convert:", roots));
                        }
                    }
                    menu::Action::SetEditor => {
                        app.workflow = Some(WorkflowState::WaitingForEditorChoice);
                        app.popup = Some(PopupState::new_text_input("Editor (nvim|vscode):"));
                    }
                    menu::Action::EditConfig => {
                        let path = config::config_path();
                        if let Err(e) = open_file_in_editor(&cfg.editor, &path, &mut terminal) {
                            app.message = Some(format!("Failed to open config: {}", e));
                        }
                    }
                },
            }
        }
    }

    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    Ok(())
}
