mod config;
mod menu;

use std::env;
use std::fs;
use std::io::{self, BufRead as _, BufReader};
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::mpsc::{self, Receiver};
use std::thread;
use std::time::Duration;

// Pull in the figlet art generated by build.rs from TITLE in build.rs
include!(concat!(env!("OUT_DIR"), "/title.rs"));

use crossterm::{
    event::{self, Event, KeyCode},
    execute,
    terminal::{disable_raw_mode, enable_raw_mode, EnterAlternateScreen, LeaveAlternateScreen},
};
use ratatui::{
    backend::CrosstermBackend,
    layout::{Alignment, Constraint, Direction, Layout, Rect},
    style::{Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Clear, List, ListItem, ListState, Paragraph},
    Terminal,
};

fn centered_rect(px: u16, py: u16, r: Rect) -> Rect {
    let vert = Layout::default()
        .direction(Direction::Vertical)
        .constraints([
            Constraint::Percentage((100 - py) / 2),
            Constraint::Percentage(py),
            Constraint::Percentage((100 - py) / 2),
        ])
        .split(r);
    Layout::default()
        .direction(Direction::Horizontal)
        .constraints([
            Constraint::Percentage((100 - px) / 2),
            Constraint::Percentage(px),
            Constraint::Percentage((100 - px) / 2),
        ])
        .split(vert[1])[1]
}

#[derive(PartialEq)]
enum PopupKind { Output, DirBrowser, TextInput }

struct PopupState {
    kind: PopupKind,
    title: String,
    items: Vec<String>,
    paths: Vec<PathBuf>,
    list_state: ListState,
    lines: Vec<String>,
    scroll: usize,
    done: bool,
    rx: Option<Receiver<Option<String>>>,
    input_value: String,
}

impl PopupState {
    fn new_output(title: &str, program: &str, args: &[&str], dir: Option<PathBuf>) -> Self {
        let (tx, rx) = mpsc::channel::<Option<String>>();
        let tx_out = tx.clone();
        let tx_err = tx.clone();
        let mut cmd = Command::new(program);
        cmd.args(args).stdout(Stdio::piped()).stderr(Stdio::piped());
        if let Some(ref d) = dir { cmd.current_dir(d); }
        match cmd.spawn() {
            Ok(mut child) => {
                let stdout = child.stdout.take().unwrap();
                let stderr = child.stderr.take().unwrap();
                let t1 = thread::spawn(move || {
                    for line in BufReader::new(stdout).lines() {
                        if let Ok(l) = line { if tx_out.send(Some(l)).is_err() { break; } }
                    }
                });
                let t2 = thread::spawn(move || {
                    for line in BufReader::new(stderr).lines() {
                        if let Ok(l) = line { if tx_err.send(Some(l)).is_err() { break; } }
                    }
                });
                thread::spawn(move || {
                    let _ = t1.join(); let _ = t2.join();
                    let _ = child.wait(); let _ = tx.send(None);
                });
            }
            Err(e) => {
                let _ = tx.send(Some(format!("Error: {}", e)));
                let _ = tx.send(None);
            }
        }
        let mut ls = ListState::default(); ls.select(Some(0));
        PopupState {
            kind: PopupKind::Output, title: title.to_string(),
            items: vec![], paths: vec![], list_state: ls,
            lines: vec![], scroll: 0, done: false, rx: Some(rx),
            input_value: String::new(),
        }
    }

    fn browser_next(&mut self) {
        let n = self.items.len(); if n == 0 { return; }
        let i = (self.list_state.selected().unwrap_or(0) + 1) % n;
        self.list_state.select(Some(i));
    }

    fn browser_prev(&mut self) {
        let n = self.items.len(); if n == 0 { return; }
        let i = (self.list_state.selected().unwrap_or(0) + n - 1) % n;
        self.list_state.select(Some(i));
    }

    fn drain_output(&mut self) {
        if let Some(ref rx) = self.rx {
            loop {
                match rx.try_recv() {
                    Ok(Some(line)) => { self.lines.push(line); self.scroll = self.lines.len().saturating_sub(1); }
                    Ok(None) => { self.done = true; break; }
                    Err(_) => break,
                }
            }
        }
    }

    fn new_dir_browser(title: &str, path: &std::path::Path) -> Self {
        let mut entries: Vec<(String, PathBuf)> = fs::read_dir(path)
            .into_iter().flatten().flatten()
            .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
            .map(|e| (e.file_name().to_string_lossy().into_owned(), e.path()))
            .collect();
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        let mut ls = ListState::default();
        if !entries.is_empty() { ls.select(Some(0)); }
        PopupState {
            kind: PopupKind::DirBrowser,
            title: title.to_string(),
            items: entries.iter().map(|(n, _)| n.clone()).collect(),
            paths: entries.into_iter().map(|(_, p)| p).collect(),
            list_state: ls,
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
        }
    }

    fn new_text_input(prompt: &str) -> Self {
        PopupState {
            kind: PopupKind::TextInput,
            title: prompt.to_string(),
            items: vec![], paths: vec![], list_state: ListState::default(),
            lines: vec![], scroll: 0, done: false, rx: None,
            input_value: String::new(),
        }
    }
}

// Tracks multi-step workflows (e.g. prompt → copy → nvim → compile)
enum WorkflowState {
    WaitingForBlankName    { templates_dir: PathBuf, projects_dir: PathBuf },
    WaitingForTemplate     { projects_dir: PathBuf },
    WaitingForTemplateName { template_path: PathBuf, projects_dir: PathBuf },
    WaitingForProject,
}

struct App {
    list_state: ListState,
    message: Option<String>,
    popup: Option<PopupState>,
    workflow: Option<WorkflowState>,
    pending_pdf: Option<PathBuf>,
}

impl App {
    fn new() -> Self {
        let mut s = ListState::default(); s.select(Some(0));
        App { list_state: s, popup: None, message: None, workflow: None, pending_pdf: None }
    }
    fn main_next(&mut self) {
        let i = (self.list_state.selected().unwrap_or(0) + 1) % menu::ITEMS.len();
        self.list_state.select(Some(i));
    }
    fn main_prev(&mut self) {
        let n = menu::ITEMS.len();
        let i = (self.list_state.selected().unwrap_or(0) + n - 1) % n;
        self.list_state.select(Some(i));
    }
}

// Internal TUI navigation actions (distinct from menu::Action which is user-facing)
enum Action {
    Quit, MainNext, MainPrev,
    ClosePopup,
    BrowserNext, BrowserPrev,
    OutputScrollUp, OutputScrollDown,
    DirBrowserConfirm,
    TextInputConfirm,
    TextInputChar(char),
    TextInputBackspace,
    MenuAction(menu::Action),
}

// ── LaTeX helpers ────────────────────────────────────────────────────────────

/// Create `.build/` and any subdirectories needed for `\include` / `\input` paths.
fn prepare_build_dir(project_dir: &std::path::Path) {
    let build = project_dir.join(".build");
    let _ = fs::create_dir_all(&build);
    if let Ok(content) = fs::read_to_string(project_dir.join("main.tex")) {
        for line in content.lines() {
            for prefix in &["\\include{", "\\input{"] {
                if let Some(start) = line.find(prefix) {
                    let rest = &line[start + prefix.len()..];
                    if let Some(end) = rest.find('}') {
                        let path = rest[..end].trim();
                        if path.contains('/') {
                            if let Some(parent) = std::path::Path::new(path).parent() {
                                let _ = fs::create_dir_all(build.join(parent));
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Prepare the build directory then spawn a compile output popup.
fn launch_compile(project_dir: PathBuf) -> PopupState {
    prepare_build_dir(&project_dir);
    let texinputs = format!(".:./Config//:{}", env::var("TEXINPUTS").unwrap_or_default());
    // Use `'...'` quoting; escape any literal single-quotes in the path
    let safe_ti = texinputs.replace('\'', "'\\''");
    // -g forces latexmk to reprocess even if it thinks nothing changed / had previous errors
    let script = format!(
        "TEXINPUTS='{}' latexmk -pdf -quiet -g -f -outdir=.build main.tex",
        safe_ti
    );
    let shell_args = ["-c", script.as_str()];
    PopupState::new_output("Compiling", "sh", &shell_args, Some(project_dir))
}

fn main() -> io::Result<()> {
    let cfg = config::load();

    enable_raw_mode()?;
    let mut stdout = io::stdout();
    execute!(stdout, EnterAlternateScreen)?;
    let backend = CrosstermBackend::new(stdout);
    let mut terminal = Terminal::new(backend)?;

    let mut app = App::new();
    let mut quit = false;

    let labels: Vec<&str> = menu::ITEMS.iter().map(|m| m.label).collect();

    while !quit {
        if let Some(ref mut p) = app.popup {
            if p.kind == PopupKind::Output { p.drain_output(); }
        }

        terminal.draw(|f| {
            let area = f.area();

            let content_area = Rect::new(0, 0, area.width, area.height);

            let chunks = Layout::default()
                .direction(Direction::Vertical)
                .constraints([
                    Constraint::Min(0),
                    Constraint::Length(3),
                ])
                .split(content_area);

            // Large font is always two lines (LaTeX / Manager stacked).
            // Small font switches to two lines when the window is narrow.
            let use_large = area.height >= 35;
            let small_wide = area.width >= 56;

            let art_height: u16 = if area.height < 20 { 1 }
                else if use_large { TITLE_LARGE_NARROW_HEIGHT }
                else if small_wide { TITLE_SMALL_WIDE_HEIGHT }
                else { TITLE_SMALL_NARROW_HEIGHT };

            let ascii_lines: Vec<Line> = if area.height < 20 {
                vec![Line::from(Span::styled(APP_TITLE, Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD)))]
            } else {
                let art: &[&str] = if use_large {
                    TITLE_LARGE_NARROW
                } else if small_wide {
                    TITLE_SMALL_WIDE
                } else {
                    TITLE_SMALL_NARROW
                };
                art.iter().map(|l| Line::from(Span::styled(*l, Style::default().fg(cfg.accent_color)))).collect()
            };

            // Outer block — one unified widget for art + items
            let menu_block = Block::default().borders(Borders::ALL);
            let menu_inner = menu_block.inner(chunks[0]);
            f.render_widget(menu_block, chunks[0]);

            // Split inner area: ASCII art top, list items below
            let inner_chunks = Layout::default()
                .direction(Direction::Vertical)
                .constraints([
                    Constraint::Length(art_height + 1),  // art lines + 1 blank gap
                    Constraint::Min(0),
                ])
                .split(menu_inner);

            let mut art_with_gap = ascii_lines;
            art_with_gap.push(Line::raw(""));
            let art = Paragraph::new(art_with_gap).alignment(Alignment::Center);
            f.render_widget(art, inner_chunks[0]);

            // Offset the list rect so "> item" block is centered as a whole
            let inner_w = menu_inner.width as usize;
            let max_item_len = labels.iter().map(|s| s.len()).max().unwrap_or(0);
            let sym_len = 2; // "> "
            let pad_left = ((inner_w.saturating_sub(max_item_len + sym_len)) / 2) as u16;
            let list_rect = Rect::new(
                inner_chunks[1].x + pad_left,
                inner_chunks[1].y,
                inner_chunks[1].width.saturating_sub(pad_left),
                inner_chunks[1].height,
            );
            let main_items: Vec<ListItem> = labels.iter()
                .map(|i| ListItem::new(*i))
                .collect();
            let main_list = List::new(main_items)
                .highlight_style(Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD))
                .highlight_symbol("> ");
            f.render_stateful_widget(main_list, list_rect, &mut app.list_state);

            let footer_text = if let Some(ref msg) = app.message {
                msg.clone()
            } else {
                "↑↓ navigate  |  Enter select  |  q quit".to_string()
            };
            let footer = Paragraph::new(footer_text)
                .alignment(Alignment::Center)
                .style(Style::default().fg(cfg.footer_color))
                .block(Block::default().borders(Borders::ALL));
            f.render_widget(footer, chunks[1]);

            // Spotlight-style popup rendered on top of content area
            if let Some(ref mut popup) = app.popup {
                match popup.kind {
                    PopupKind::DirBrowser => {
                        let popup_area = centered_rect(60, 70, content_area);
                        f.render_widget(Clear, popup_area);
                        let items: Vec<ListItem> = popup.items.iter()
                            .map(|i| ListItem::new(i.as_str())).collect();
                        let hint = "\u{2191}\u{2193} navigate  \u{23ce} select  Esc cancel";
                        let list = List::new(items)
                            .block(Block::default()
                                .title(format!(" {}  ({}) ", popup.title, hint))
                                .borders(Borders::ALL))
                            .highlight_style(Style::default().fg(cfg.accent_color).add_modifier(Modifier::BOLD))
                            .highlight_symbol("> ");
                        f.render_stateful_widget(list, popup_area, &mut popup.list_state);
                    }
                    PopupKind::Output => {
                        let popup_area = centered_rect(80, 80, content_area);
                        f.render_widget(Clear, popup_area);
                        let inner_h = popup_area.height.saturating_sub(2) as usize;
                        let start = popup.scroll.saturating_sub(inner_h.saturating_sub(1));
                        let visible: Vec<ListItem> = popup.lines.iter()
                            .skip(start).take(inner_h)
                            .map(|l| ListItem::new(l.as_str())).collect();
                        let status = if popup.done { " [done - Esc to close]" } else { " [running...]" };
                        let list = List::new(visible).block(
                            Block::default()
                                .title(format!(" {}{} ", popup.title, status))
                                .borders(Borders::ALL));
                        f.render_widget(list, popup_area);
                    }
                    PopupKind::TextInput => {
                        let popup_area = centered_rect(55, 22, content_area);
                        f.render_widget(Clear, popup_area);
                        let display = format!("{}\u{258c}", popup.input_value);
                        let widget = Paragraph::new(vec![
                            Line::raw(""),
                            Line::from(format!("  {}", display)),
                            Line::raw(""),
                            Line::from(Span::styled(
                                "  \u{23ce} confirm  |  Esc cancel",
                                Style::default().fg(cfg.footer_color),
                            )),
                        ])
                        .block(Block::default()
                            .title(format!(" {} ", popup.title))
                            .borders(Borders::ALL));
                        f.render_widget(widget, popup_area);
                    }
                }
            }

        })?;

        let streaming = matches!(&app.popup, Some(p) if p.kind == PopupKind::Output && !p.done);
        let timeout = if streaming { Duration::from_millis(100) } else { Duration::from_secs(60) };
        if !event::poll(timeout)? { continue; }

        let Event::Key(key) = event::read()? else { continue; };
        app.message = None;

        let action: Option<Action> = if let Some(ref popup) = app.popup {
            match popup.kind {
                PopupKind::DirBrowser => match key.code {
                    KeyCode::Up    => Some(Action::BrowserPrev),
                    KeyCode::Down  => Some(Action::BrowserNext),
                    KeyCode::Esc   => Some(Action::ClosePopup),
                    KeyCode::Enter => Some(Action::DirBrowserConfirm),
                    _ => None,
                },
                PopupKind::TextInput => match key.code {
                    KeyCode::Esc       => Some(Action::ClosePopup),
                    KeyCode::Enter     => Some(Action::TextInputConfirm),
                    KeyCode::Char(c)   => Some(Action::TextInputChar(c)),
                    KeyCode::Backspace => Some(Action::TextInputBackspace),
                    _ => None,
                },
                PopupKind::Output => match key.code {
                    KeyCode::Up   => Some(Action::OutputScrollUp),
                    KeyCode::Down => Some(Action::OutputScrollDown),
                    KeyCode::Esc if popup.done => Some(Action::ClosePopup),
                    _ => None,
                },
            }
        } else {
            match key.code {
                KeyCode::Up            => Some(Action::MainPrev),
                KeyCode::Down          => Some(Action::MainNext),
                KeyCode::Char('q') | KeyCode::Esc => Some(Action::Quit),
                KeyCode::Enter => {
                    let idx = app.list_state.selected().unwrap_or(0);
                    menu::ITEMS.get(idx)
                        .map(|item| Action::MenuAction((item.action)()))
                }
                _ => None,
            }
        };

        if let Some(action) = action {
            match action {
                Action::Quit => quit = true,
                Action::MainNext => app.main_next(),
                Action::MainPrev => app.main_prev(),
                Action::ClosePopup => {
                    // When closing a finished compile popup, open the PDF
                    if matches!(&app.popup, Some(p) if p.kind == PopupKind::Output) {
                        if let Some(pdf) = app.pending_pdf.take() {
                            if pdf.exists() {
                                disable_raw_mode()?;
                                execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                                let mut parts = cfg.pdf_viewer.split_whitespace();
                                let ok = if let Some(prog) = parts.next() {
                                    Command::new(prog).args(parts).arg(&pdf).status()
                                        .map(|s| s.success()).unwrap_or(false)
                                } else { false };
                                if !ok {
                                    let _ = Command::new("open").arg(&pdf).status();
                                }
                                enable_raw_mode()?;
                                execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                                terminal.clear()?;
                            } else {
                                app.message = Some(
                                    "Compilation failed \u{2014} run latexmk manually to see errors.".to_string()
                                );
                            }
                        }
                    }
                    app.workflow = None;
                    app.popup = None;
                }
                // (ClosePopupWithMsg removed — no longer needed)
                Action::BrowserNext => { if let Some(ref mut p) = app.popup { p.browser_next(); } }
                Action::BrowserPrev => { if let Some(ref mut p) = app.popup { p.browser_prev(); } }
                Action::OutputScrollUp => {
                    if let Some(ref mut p) = app.popup { p.scroll = p.scroll.saturating_sub(1); }
                }
                Action::OutputScrollDown => {
                    if let Some(ref mut p) = app.popup {
                        p.scroll = (p.scroll + 1).min(p.lines.len().saturating_sub(1));
                    }
                }
                Action::DirBrowserConfirm => {
                    let selected = app.popup.as_ref().and_then(|p| {
                        p.list_state.selected().and_then(|i| p.paths.get(i).cloned())
                    });
                    let workflow = app.workflow.take();
                    app.popup = None;
                    match (selected, workflow) {
                        (Some(template_path), Some(WorkflowState::WaitingForTemplate { projects_dir })) => {
                            app.workflow = Some(WorkflowState::WaitingForTemplateName { template_path, projects_dir });
                            app.popup = Some(PopupState::new_text_input("Enter project name:"));
                        }
                        (Some(project_dir), Some(WorkflowState::WaitingForProject)) => {
                            disable_raw_mode()?;
                            execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                            let _ = Command::new("nvim").arg("main.tex").current_dir(&project_dir).status();
                            enable_raw_mode()?;
                            execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                            terminal.clear()?;
                            app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                            app.popup = Some(launch_compile(project_dir));
                        }
                        _ => { app.message = Some("Nothing selected.".to_string()); }
                    }
                }
                Action::TextInputChar(c) => {
                    if let Some(ref mut p) = app.popup { p.input_value.push(c); }
                }
                Action::TextInputBackspace => {
                    if let Some(ref mut p) = app.popup { p.input_value.pop(); }
                }
                Action::TextInputConfirm => {
                    let name = app.popup.as_ref()
                        .map(|p| p.input_value.trim().to_string())
                        .unwrap_or_default();
                    if name.is_empty() {
                        app.message = Some("Project name cannot be empty.".to_string());
                    } else {
                        let workflow = app.workflow.take();
                        app.popup = None;
                        match workflow {
                            Some(WorkflowState::WaitingForBlankName { templates_dir, projects_dir }) => {
                                let project_dir = projects_dir.join(&name);
                                let _ = fs::create_dir_all(&project_dir);
                                let src = templates_dir.join("main.tex");
                                if src.exists() { let _ = fs::copy(&src, project_dir.join("main.tex")); }
                                disable_raw_mode()?;
                                execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                                let _ = Command::new("nvim").arg("main.tex").current_dir(&project_dir).status();
                                enable_raw_mode()?;
                                execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                                terminal.clear()?;
                                app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                app.popup = Some(launch_compile(project_dir));
                            }
                            Some(WorkflowState::WaitingForTemplateName { template_path, projects_dir }) => {
                                let project_dir = projects_dir.join(&name);
                                let _ = fs::create_dir_all(&project_dir);
                                let src = format!("{}/", template_path.display());
                                let _ = Command::new("rsync")
                                    .args([
                                        "-a",
                                        "--exclude=.build",
                                        "--exclude=*.aux",
                                        "--exclude=*.log",
                                        "--exclude=*.fdb_latexmk",
                                        "--exclude=*.fls",
                                        "--exclude=*.synctex.gz",
                                        "--exclude=*.toc",
                                        "--exclude=*.out",
                                        "--exclude=missfont.log",
                                        "--exclude=main.pdf",
                                        &src,
                                        project_dir.to_str().unwrap_or("."),
                                    ])
                                    .status();
                                disable_raw_mode()?;
                                execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                                let _ = Command::new("nvim").arg("main.tex").current_dir(&project_dir).status();
                                enable_raw_mode()?;
                                execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                                terminal.clear()?;
                                app.pending_pdf = Some(project_dir.join(".build").join("main.pdf"));
                                app.popup = Some(launch_compile(project_dir));
                            }
                            _ => {}
                        }
                    }
                }
                Action::MenuAction(menu_action) => match menu_action {
                    menu::Action::Quit => quit = true,
                    menu::Action::LaunchOutput { title, program, args, dir } => {
                        let args_ref: Vec<&str> = args.iter().map(|s| s.as_str()).collect();
                        app.popup = Some(PopupState::new_output(&title, &program, &args_ref, dir));
                    }
                    menu::Action::RunInteractive { program, args, dir } => {
                        disable_raw_mode()?;
                        execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
                        let mut cmd = Command::new(&program);
                        cmd.args(&args);
                        if let Some(ref d) = dir { cmd.current_dir(d); }
                        let _ = cmd.status();
                        enable_raw_mode()?;
                        execute!(terminal.backend_mut(), EnterAlternateScreen)?;
                        terminal.clear()?;
                    }
                    menu::Action::RevealInFinder { path } => {
                        let _ = Command::new("open").arg(&path).spawn();
                        app.message = Some("Opened in Finder".to_string());
                    }
                    menu::Action::CreateBlankProject { templates_dir, projects_dir } => {
                        app.workflow = Some(WorkflowState::WaitingForBlankName { templates_dir, projects_dir });
                        app.popup = Some(PopupState::new_text_input("Enter project name:"));
                    }
                    menu::Action::CreateFromTemplate { templates_dir, projects_dir } => {
                        if !templates_dir.is_dir() {
                            app.message = Some(format!("Templates dir not found: {}", templates_dir.display()));
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForTemplate { projects_dir });
                            app.popup = Some(PopupState::new_dir_browser("Select a template:", &templates_dir));
                        }
                    }
                    menu::Action::OpenLatexProject { projects_dir } => {
                        if !projects_dir.is_dir() {
                            app.message = Some(format!("Projects dir not found: {}", projects_dir.display()));
                        } else {
                            app.workflow = Some(WorkflowState::WaitingForProject);
                            app.popup = Some(PopupState::new_dir_browser("Select a project:", &projects_dir));
                        }
                    }
                },
            }
        }
    }

    disable_raw_mode()?;
    execute!(terminal.backend_mut(), LeaveAlternateScreen)?;
    Ok(())
}
